// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyycVNQpi7Lb7WRZ21jPU1pARSOkHCv7s',
    appId: '1:1029872695934:web:de84f28a4165b3ed5fb62f',
    messagingSenderId: '1029872695934',
    projectId: 'bula-bnb',
    authDomain: 'bula-bnb.firebaseapp.com',
    databaseURL: 'https://bula-bnb-default-rtdb.firebaseio.com',
    storageBucket: 'bula-bnb.appspot.com',
    measurementId: 'G-TB66LS0NT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-gvdOZWUvY-VIqm-QHEXLxfCBzVB_3TE',
    appId: '1:1029872695934:android:796abe748b82485a5fb62f',
    messagingSenderId: '1029872695934',
    projectId: 'bula-bnb',
    databaseURL: 'https://bula-bnb-default-rtdb.firebaseio.com',
    storageBucket: 'bula-bnb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTQtCekIMvpw8XumG_jEICeySqrtIDBs',
    appId: '1:1029872695934:ios:9331d9f0f7bb75dc5fb62f',
    messagingSenderId: '1029872695934',
    projectId: 'bula-bnb',
    databaseURL: 'https://bula-bnb-default-rtdb.firebaseio.com',
    storageBucket: 'bula-bnb.appspot.com',
    iosClientId: '1029872695934-8a0mgnvs4u5mcajado07pcj5tr5dbci7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTQtCekIMvpw8XumG_jEICeySqrtIDBs',
    appId: '1:1029872695934:ios:21a83707573e25805fb62f',
    messagingSenderId: '1029872695934',
    projectId: 'bula-bnb',
    databaseURL: 'https://bula-bnb-default-rtdb.firebaseio.com',
    storageBucket: 'bula-bnb.appspot.com',
    iosClientId: '1029872695934-cuknt9kd4quknpavdee8pbu61k1bf1do.apps.googleusercontent.com',
    iosBundleId: 'com.example.bula.RunnerTests',
  );
}
